cloud_ldap:
  main:
    object_class: 'Cloud\LdapBundle\Entity\User'
    object_forms:
      - 'Cloud\FrontBundle\Form\Type\UserType'
      - 'Cloud\FrontBundle\Form\Type\ProfileType'
  services:
    git_gogs:
      enable: true
      default: true
      object_class: 'Cloud\LdapBundle\Entity\Service'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
    mail:
      enable: true
      default: true
      object_class: 'Cloud\LdapBundle\Entity\Service'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
    seafile:
      enable: true
      default: true
      object_class: 'Cloud\LdapBundle\Entity\Service'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
    ampache:
      enable: true
      default: false
      object_class: 'Cloud\LdapBundle\Entity\Service'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
    radicale:
      enable: true
      default: true
      object_class: 'Cloud\LdapBundle\Entity\Service'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
    freeradius:
      enable: true
      default: false
      object_class: 'Cloud\LdapBundle\Entity\FreeRadiusService'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
    posix:
      enable: true
      default: false
      object_class: 'Cloud\LdapBundle\Entity\PosixService'
      object_forms:
        - 'Cloud\FrontBundle\Form\Type\PosixType'
        - 'Cloud\FrontBundle\Form\Type\ServiceMultiPasswordType'
        - 'Cloud\FrontBundle\Form\Type\PublicKeyType'