cloud_registration:
    resource: "@CloudRegistrationBundle/Controller/"
    type:     annotation
    prefix:   /reg

cloud_front:
    resource: "@CloudFrontBundle/Controller/"
    type:     annotation


