

services:
    cloud.ldap.util.usermanipulator:
        class: Cloud\LdapBundle\Util\UserManipulator
        arguments:
            - "@cloud.ldap.client.root"
            - "@validator"
            - "%ldap_base_dn%"
            - "%ldap_bind_rdn%"
            - "%ldap_bind_pw%"
            - "%cloud_ldap.services%"
            - "%domain%"
    cloud.ldap.util.groupmanipulator:
        class: Cloud\LdapBundle\Util\GroupManipulator
        arguments:
            - "@cloud.ldap.client.root"
            - "@validator"
            - "%ldap_base_dn%"
            - "%ldap_bind_rdn%"
            - "%ldap_bind_pw%"
            - "%cloud_ldap.services%"
            - "%domain%"
    cloud.ldap.userprovider:
        class: Cloud\LdapBundle\Security\LdapUserProvider
        arguments:
            - "@cloud.ldap.client"
            - "%ldap_base_dn%"
            - "%ldap_bind_rdn%"
            - "%ldap_bind_pw%"
            - ["ROLE_USER"]
            - "uid"
            - "({uid_key}={username})"
            - "%cloud_ldap.services%"
            - "@cloud.ldap.annation.reader"
            - "@cloud.ldap.groupprovider"
    cloud.ldap.groupprovider:
        class: Cloud\LdapBundle\Security\LdapGroupProvider
        arguments:
            - "@logger"
            - "@cloud.ldap.client"
            - "%ldap_base_dn%"
            - "%ldap_bind_rdn%"
            - "%ldap_bind_pw%"
            - "@cloud.ldap.annation.reader"
    user.check:
        class: Symfony\Component\Security\Core\User\UserChecker
    cloud.ldap.authenticationprovider:
        class: Cloud\LdapBundle\Security\LdapBindAuthenticationProvider
        arguments:
            - "@cloud.ldap.userprovider"
            - "@user.check"
            - "default"
            - "@cloud.ldap.client"
            - "uid={username},ou=Users,%ldap_base_dn%"
            - true
    cloud.ldap.client:
        class: Cloud\LdapBundle\Services\LdapClient
        arguments: [ "%ldap_host%", "%ldap_port%", 3, "%ldap_ssl%", "%use_start_tls%" ]
    cloud.ldap.client.root:
        class: Cloud\LdapBundle\Services\LdapClient
        arguments: [ "%ldap_host%", "%ldap_port%", 3, "%ldap_ssl%", "%use_start_tls%" ]
    cloud.encoder.crypt:
        class: Cloud\LdapBundle\Security\CryptEncoder
    cloud.ldap.schema.manipulator:
        class: Cloud\LdapBundle\Util\SchemaManipulator
        arguments:
          - "@logger"
          - "@cloud.ldap.userprovider"
          - "@cloud.ldap.util.usermanipulator"
          - "@cloud.ldap.client.root"
          - "%ldap_bind_rdn%"
          - "%ldap_bind_pw%"
          - "%ldap_base_dn%"
          - "%cloud_ldap.services%"
          - "%domain%"
    cloud.ldap.annation.reader:
        class: Doctrine\Common\Annotations\AnnotationReader
    cloud.ldap.rehasher:
        class: Cloud\LdapBundle\Security\Rehasher
        tags:
        - { name: kernel.event_listener, event: security.interactive_login }
        arguments:
        - "@logger"
        - "@cloud.ldap.util.usermanipulator"

    security.authentication.provider.ldap_bind:
        class: Cloud\LdapBundle\Security\LdapBindAuthenticationProvider
        arguments: [none,none,none,none,none,"%security.authentication.hide_user_not_found%"]
