

services:
    cloud.ldap.util.usermanipulator:
        class: Cloud\LdapBundle\Util\UserManipulator
        arguments:
            - "@cloud.ldap.client.root"
            - "@cloud.encoder.crypt"
            - "@validator"
            - "%ldap_base_dn%"
            - "%ldap_bind_rdn%"
            - "%ldap_bind_pw%"
    cloud.ldap.userprovider:
        class: Cloud\LdapBundle\Security\LdapUserProvider
        arguments:
            - "@cloud.ldap.client"
            - "%ldap_base_dn%"
            - "%ldap_bind_rdn%"
            - "%ldap_bind_pw%"
            - ["ROLE_USER"]
            - "uid"
            - "({uid_key}={username})"
            - "%services%"
    user.check:
        class: Symfony\Component\Security\Core\User\UserChecker
    cloud.ldap.authenticationprovider:
        class: Cloud\LdapBundle\Security\LdapBindAuthenticationProvider
        arguments:
            - "@cloud.ldap.userprovider"
            - "@user.check"
            - "default"
            - "@cloud.ldap.client"
            - "uid={username},ou=Users,%ldap_base_dn%"
            - true
    cloud.ldap.client:
        class: Cloud\LdapBundle\Services\LdapClient
    cloud.ldap.client.root:
        class: Cloud\LdapBundle\Services\LdapClient
        arguments: [ "%ldap_host%" ]
    cloud.encoder.crypt:
        class: Cloud\LdapBundle\Security\CryptEncoder